### ISSUE TITLE
Missing major version tags to support action use

### ISSUE THREAD

**Issue by stevenh** [bufbuild/buf-setup-action#153]
It's idiomatic to create major version tags so users can use them in their actions reducing code churn to get the latest compatible version e.g.
`bufbuild/buf-setup-action@v1`

Could you add the creation of:
* `v<major>`

You can see this in practice [actions/checkout](https://github.com/actions/checkout/tags).

**Comment by stevenh** [comment]
@rhbuf @doriable could you have a look at this, shouldn't take long and would be a nice quality of life for all buf-setup-action users?

**Comment by stefanvanburen** [comment]
Hi @stevenh - I believe this is already possible without needing a specific `v1` git tag - you can already use the syntax you have above and get the latest version of `buf`.

For example we're using this syntax over in bufbuild/modules to grab the latest `buf` without needing to bump it each time:

https://github.com/bufbuild/plugins/blob/60f14eac9354d54a0593e12664f6139ddf387e2d/.github/workflows/ci.yml#L74

Does that answer your question, or is there something else you're looking for?

**Comment by mfridman** [comment]
I think it's recommended, but not mandatory to have a tagged major `vN`. So I'm also curious what issue you're running into?

> We recommend creating releases using semantically versioned tags – for example, v1.1.3 – **and keeping major (v1) and minor (v1.1) tags current to the latest appropriate commit.** For more information, see "[About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)" and "[About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).

[GitHub Reference](https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#setting-up-github-actions-workflows)

> **Move the major version tag (such as v1, v2) to point to the Git ref of the current release.** For more information, see "[Git basics - tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)."

[GitHub Reference](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)
