### ISSUE TITLE
Cannot get versions past the first page of Release API results 

### ISSUE THREAD

**Issue by rodaine** [bufbuild/buf-setup-action#18]
Hey, folks! Ran into a weird bug today with this action. On a PR, v0.41.0 of buf was configured to be run against but we received the following error:

```
Run bufbuild/buf-setup-action@v0.1.0
Setting up buf version "0.41.0"
Resolving the download URL for the current platform...
Error: Unable to find Buf version "0.41.0" for platform "Linux" and architecture "x86_64".
```

The release does exist, and has a Linux/x86_64 version available to download, and there are currently no incidents on the GH APIs. Looking into the action's definition further, the [List Releases](https://docs.github.com/en/rest/reference/repos#list-releases) endpoint is called, but [without pagination](https://github.com/bufbuild/buf-setup-action/blob/3424b70/src/buf.ts#L115-L121). This causes the API to default to 30 results per page, and as of the release of v1.0.0-rc8 two hours ago, v0.41.0 became the 31st release. 

We encountered this on v0.1.0 of the Action, but this affects all versions through latest.

**Comment by amckinney** [comment]
Thanks for all the context @rodaine! It looks like we'll need to support pagination to fix your issue, but in the meantime are you able to upgrade to the latest version? Ideally, we don't have users on a release more than 100 release ago, so there might even be an argument against the pagination (but we should probably still do it for completeness).

**Comment by rodaine** [comment]
We will be upgrading to a more recent release, but if you don't want to support an existing release version the error should reflect that (took me about 30min to figure out why our CI decided to break out from underneath us).

Also, it might be more efficient anyways to lookup the releases by tag directly: 
https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name

**Comment by rodaine** [comment]
(Slight correction above, max allowed page size is 100, the default is 30. Same overall behavior, though)

**Comment by doriable** [comment]
A fix has been put through with a release (https://github.com/bufbuild/buf-setup-action/releases/tag/v0.7.0), please feel free to re-open the ticket if anything else comes up. Thanks!
