### ISSUE TITLE
Use latest buf when use Github action Setup buf without specifying version

### ISSUE THREAD

**Issue by hojongs** [bufbuild/buf-setup-action#2]
Hi, I'm trying to use github action Setup buf.

I couldn't find document for the github action except of https://github.com/marketplace/actions/setup-buf
If you have a document for it, please let me know.

Anyway, I tried wizhi/setup-buf@v1 without `with.version` option.

```yml
      - uses: wizhi/setup-buf@v1 # no specify with.version option
      - run: buf --version
```

I expect to use latest version of buf. (current latest version is 0.41.0)
But, I got output `0.18.0`, not `0.41.0`
`0.18.0` even doesn't contain build command. So, I think it's too low version as default version.

So I want to suggest that use latest buf when use the github action without with.version option
Assuming that latest version is `0.41.0`, these below github action workflows should print same output. (`0.41.0`)

```yml
      - uses: wizhi/setup-buf@v1
      - run: buf --version
```

```yml
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.41.0
      - run: buf --version
```

**Comment by amckinney** [comment]
Thanks for the issue! We recently released our own curated set of [Buf GitHub Actions](https://blog.buf.build/2021/04/20/github-actions-for-buf-now-available/), which includes the [buf-setup](https://github.com/marketplace/actions/buf-setup) action.

The `buf-setup` action already supports what you're suggesting in its [action.yml](https://github.com/bufbuild/buf-setup-action/blob/d99f59bee3483c4dba8cded4c8b8e55e6d607e1c/action.yml#L11), so you should be good to go if you use it instead.

**Comment by hojongs** [comment]
Ah--- sorry, I misunderstood that github.com/marketplace/actions/setup-buf is owned by this repo, but it's not.
Ok, let me try this one: https://github.com/marketplace/actions/buf-setup
Thank you for your fast answer!
