### ISSUE TITLE
Rename buf_api_token to buf_token

### ISSUE THREAD

**Issue by hariso** [bufbuild/buf-setup-action#217]
... or vice versa.:)

Firstly, thanks for this great product and also for all these GH actions!

I'd like to suggest renaming the configuration parameter `buf_api_token` to `buf_token` since that's what most (all?) other Buf actions use (lint, breaking, push).

**Comment by emcfarlane** [comment]
Hey @hariso , we have recently v1 buf's new GitHub action [`buf-action`](https://github.com/bufbuild/buf-action). This has the input configuration `token`. Please take a look!

**Comment by hariso** [comment]
Whoops, embarrassing :D 

Thanks @emcfarlane !
