### ISSUE TITLE
Ability to set BUF_TOKEN

### ISSUE THREAD

**Issue by vh** [bufbuild/buf-setup-action#23]
Not just only with buf-push action.
To be able to run the following command: `buf generate buf.build/<org>/<repo>`.

**Comment by WillAbides** [comment]
Setting `BUF_TOKEN` is better left to the workflow that will be running the buf command. You should create a `BUF_TOKEN` secret in the GitHub repository and add this to the workflow definition:

```yaml
env:
    BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
```

**Comment by vh** [comment]
That works! Thanks!
