### ISSUE TITLE
Add support for linux/aarch64 downloads

### ISSUE THREAD

**Issue by thejerrybao** [bufbuild/buf-setup-action#66]
https://github.com/bufbuild/buf-setup-action/issues/9 added support for ARM environments, but no download exists for buf with the format `buf-Linux-arm64`. One does exist for `buf-Linux-aarch64` which is probably what should be downloaded.

**Comment by emcfarlane** [comment]
Hi @thejerrybao , this has been fixed in the new [`buf-action`](https://github.com/bufbuild/buf-action), see https://github.com/bufbuild/buf-action/blob/0d29f75678c02558bc41282d46e8de517946a751/src/installer.ts#L134
